create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists public.academy_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  role text not null default 'learner' check (role in ('owner', 'learner')),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.academy_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.academy_profiles(id) on delete cascade,
  recipient_id uuid not null references public.academy_profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id)
);

create table if not exists public.academy_auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.academy_profiles(id) on delete cascade,
  event_type text not null check (event_type in ('login', 'registration')),
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.academy_profiles enable row level security;
alter table public.academy_messages enable row level security;
alter table public.academy_auth_events enable row level security;

grant select on public.academy_profiles to authenticated;
grant update (last_seen_at, updated_at) on public.academy_profiles to authenticated;
grant select, insert on public.academy_messages to authenticated;
grant update (read_at) on public.academy_messages to authenticated;
grant select, insert on public.academy_auth_events to authenticated;
grant usage, select on sequence public.academy_messages_id_seq to authenticated;
grant usage, select on sequence public.academy_auth_events_id_seq to authenticated;

create or replace function private.is_academy_owner() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.academy_profiles where id = (select auth.uid()) and role = 'owner');
$$;
create or replace function private.academy_owner_id() returns uuid
language sql stable security definer set search_path = '' as $$
  select id from public.academy_profiles where role = 'owner' order by created_at limit 1;
$$;
revoke all on function private.is_academy_owner() from public, anon;
revoke all on function private.academy_owner_id() from public, anon;
grant execute on function private.is_academy_owner() to authenticated;
grant execute on function private.academy_owner_id() to authenticated;

create policy "Academy participants read relevant profiles" on public.academy_profiles
for select to authenticated using (id = (select auth.uid()) or role = 'owner' or (select private.is_academy_owner()));
create policy "Learners update their own presence" on public.academy_profiles
for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "Participants read their messages" on public.academy_messages
for select to authenticated using (sender_id = (select auth.uid()) or recipient_id = (select auth.uid()));
create policy "Participants send permitted messages" on public.academy_messages
for insert to authenticated with check (
  sender_id = (select auth.uid()) and ((select private.is_academy_owner()) or recipient_id = (select private.academy_owner_id()))
);
create policy "Recipients mark messages read" on public.academy_messages
for update to authenticated using (recipient_id = (select auth.uid())) with check (recipient_id = (select auth.uid()));
create policy "Users record their auth events" on public.academy_auth_events
for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Owners read auth events" on public.academy_auth_events
for select to authenticated using ((select private.is_academy_owner()));

create or replace function private.create_academy_profile() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.academy_profiles (id, display_name, role)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, 'Learner'), '@', 1)), 'learner')
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function private.create_academy_profile() from public, anon, authenticated;
create trigger create_academy_profile_after_signup after insert on auth.users
for each row execute function private.create_academy_profile();

insert into public.academy_profiles (id, display_name, role)
select id, coalesce(nullif(raw_user_meta_data ->> 'display_name', ''), split_part(email, '@', 1)),
  case when lower(email) = 'og@og-web.site' then 'owner' else 'learner' end
from auth.users on conflict (id) do update set display_name = excluded.display_name, role = excluded.role, updated_at = now();

alter publication supabase_realtime add table public.academy_messages;
alter publication supabase_realtime add table public.academy_profiles;
alter publication supabase_realtime add table public.academy_auth_events;
