create table if not exists public.academy_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  status text not null default 'started' check (status in ('started', 'completed')),
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

alter table public.academy_progress enable row level security;
grant select, insert, update, delete on public.academy_progress to authenticated;
grant usage, select on sequence public.academy_progress_id_seq to authenticated;

create policy "Learners read their own progress" on public.academy_progress for select to authenticated using ((select auth.uid()) = user_id);
create policy "Learners create their own progress" on public.academy_progress for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Learners update their own progress" on public.academy_progress for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Learners delete their own progress" on public.academy_progress for delete to authenticated using ((select auth.uid()) = user_id);
